"""Offline four-chain synthetic benchmark with saved arrays and diagnostic plots."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

import inv_compy as inv
from compy_diagnostics import save_run, summarize_chains


def run(output, *, iterations=1000, burnin=250, chains=4):
    """Exercise noisy synthetic data and a deliberately biased starting model.

    This short benchmark tests workflow behavior, not posterior convergence or
    uniqueness of velocity recovery. All chains use the same prior-defining model.
    """
    if any(
        isinstance(x, bool) or not isinstance(x, int)
        for x in (iterations, burnin, chains)
    ):
        raise ValueError("iterations, burnin and chains must be integers")
    if chains < 2 or burnin < 0 or iterations - burnin < 4:
        raise ValueError("Need two chains and at least four post-burn-in iterations")
    output = Path(output)
    if output.exists():
        raise FileExistsError(f"Output already exists: {output}")
    truth = np.array(
        [
            [100.0, 2200.0, 3000.0, 1500.0],
            [1000.0, 2800.0, 6000.0, 3500.0],
            [0.0, 3300.0, 8000.0, 4500.0],
        ]
    )
    starting = truth.copy()
    starting[0, 3] = 1800
    frequency = np.linspace(0.005, 0.02, 12)
    clean = inv.calc_norm_compliance(4000, frequency, truth)
    uncertainty = 0.03 * np.abs(clean)
    observed = clean + np.random.default_rng(2026).normal(0, uncertainty)
    results = [
        inv.invert_compliance_beta(
            observed,
            frequency,
            4000,
            starting_model=starting,
            s=uncertainty,
            iteration=iterations,
            sigma_v=35,
            sigma_h=8,
            alpha=0,
            seed=seed,
            return_profiles=False,
        )
        for seed in range(chains)
    ]
    models = np.stack([result[0] for result in results])
    predictions = np.stack([result[4] for result in results])
    misfit = np.stack([result[3][0] for result in results])
    acceptance = np.array([result[-1] for result in results])
    # Diagnose all sampled model variables plus the data misfit. Density, Vp,
    # the half-space and total finite depth are fixed and deliberately excluded.
    draws = np.stack(
        [
            models[:, 0, 3, :],
            models[:, 1, 3, :],
            models[:, 0, 0, :],
            models[:, 1, 0, :],
            misfit,
        ],
        axis=-1,
    )
    report = summarize_chains(
        draws,
        [
            "Vs_layer_1_m_s",
            "Vs_layer_2_m_s",
            "thickness_layer_1_m",
            "thickness_layer_2_m",
            "weighted_residual_norm",
        ],
        burnin=burnin,
    )
    report["initial_weighted_residual_norm"] = float(misfit[0, 0])
    report["best_retained_weighted_residual_norm"] = float(misfit[:, burnin:].min())
    report["acceptance_per_chain"] = acceptance.tolist()
    report["warnings"].append(
        "Chains share the same starting state and prior bounds. Low Rhat alone "
        "cannot establish exploration of other modes or unique model recovery."
    )
    report["benchmark"] = (
        "Noisy synthetic observations generated by ComPy's own forward solver."
    )
    settings = dict(
        iterations=iterations,
        burnin=burnin,
        chains=chains,
        seeds=list(range(chains)),
        noise_seed=2026,
        water_depth_m=4000,
        relative_noise=0.03,
        sigma_v_m_s=35,
        sigma_h_m=8,
        alpha=0,
        sampler="invert_compliance_beta",
        return_profiles=False,
        units=dict(
            frequency="Hz",
            compliance="1/Pa",
            thickness="m",
            density="kg/m^3",
            velocity="m/s",
        ),
    )
    save_run(
        output,
        dict(
            truth=truth,
            starting_model=starting,
            frequency=frequency,
            clean_compliance=clean,
            observed_compliance=observed,
            uncertainty=uncertainty,
            models=models,
            predictions=predictions,
            weighted_residual_norm=misfit,
            acceptance=acceptance,
        ),
        settings=settings,
        diagnostics=report,
    )
    fig, axes = plt.subplots(1, 3, figsize=(16, 4), constrained_layout=True)
    for index in range(chains):
        axes[0].plot(misfit[index], lw=0.8, label=f"Chain {index + 1}")
    axes[0].axvline(burnin, color="black", linestyle="--", label="Burn-in")
    axes[0].set(xlabel="Saved iteration", ylabel="Weighted residual norm")
    axes[0].legend(fontsize=8)
    retained = predictions[:, burnin:, :].reshape(-1, len(frequency))
    lo, median, hi = np.quantile(retained, [0.05, 0.5, 0.95], axis=0)
    axes[1].errorbar(
        frequency, observed, yerr=uncertainty, fmt="o", label="Noisy observations"
    )
    axes[1].plot(frequency, clean, color="black", label="Known synthetic truth")
    axes[1].plot(frequency, median, label="Retained prediction median")
    axes[1].fill_between(frequency, lo, hi, alpha=0.25, label="Retained 5–95% range")
    axes[1].set(xlabel="Frequency (Hz)", ylabel="Normalized compliance (1/Pa)")
    axes[1].legend(fontsize=8)
    for index in range(chains):
        axes[2].plot(models[index, 0, 3], lw=0.8, label=f"Chain {index + 1}")
    axes[2].axhline(truth[0, 3], color="black", linestyle=":", label="Known truth")
    axes[2].axvline(burnin, color="black", linestyle="--")
    axes[2].set(xlabel="Saved iteration", ylabel="Shallow-layer Vs (m/s)")
    axes[2].legend(fontsize=8)
    fig.suptitle("Synthetic workflow benchmark — inspect diagnostics before inference")
    fig.savefig(output / "diagnostics.png", dpi=150)
    fig.savefig(output / "diagnostics.svg", metadata={"Date": None})
    plt.close(fig)
    print(f"Saved arrays, metadata, checksums and diagnostics to {output}")
    print(
        f"Initial / best retained residual: {misfit[0, 0]:.3f} / {misfit[:, burnin:].min():.3f}"
    )
    for message in report["warnings"]:
        print(f"Warning: {message}")
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("synthetic-results"))
    parser.add_argument("--iterations", type=int, default=1000)
    parser.add_argument("--burnin", type=int, default=250)
    parser.add_argument("--chains", type=int, default=4)
    args = parser.parse_args()
    run(args.output, iterations=args.iterations, burnin=args.burnin, chains=args.chains)


if __name__ == "__main__":
    main()
